// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc_Kf261bHoPqwJcB_Z6VBKeYX8iIFbKQ',
    appId: '1:780685111167:web:248cf8576adf048165f44a',
    messagingSenderId: '780685111167',
    projectId: 'codea-6d3fa',
    authDomain: 'codea-6d3fa.firebaseapp.com',
    storageBucket: 'codea-6d3fa.appspot.com',
    measurementId: 'G-8Q3CR2634N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJv3YY-mVXNPc25Oo6iIFhsv5z7FmUg34',
    appId: '1:780685111167:android:976d801e48a5ee7965f44a',
    messagingSenderId: '780685111167',
    projectId: 'codea-6d3fa',
    storageBucket: 'codea-6d3fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_xb3uVbamooBWdbsh1YpvoGxMAoPbT_w',
    appId: '1:780685111167:ios:a3f1900614be0f6a65f44a',
    messagingSenderId: '780685111167',
    projectId: 'codea-6d3fa',
    storageBucket: 'codea-6d3fa.appspot.com',
    iosBundleId: 'com.ucl.codeamor.codeamor',
  );
}
